DELIMITER //

CREATE PROCEDURE SP_RUN_DETERMINATION()
BEGIN
    -- 1. 이전 판정 기록을 초기화합니다.
    TRUNCATE TABLE DETERMINATION;

    -- 2. 최종 판정 로직을 실행하여 새 결과를 삽입합니다.
    INSERT INTO DETERMINATION (
        DETERM_ID, USER_ID, CRITERIA_ID, DETERM_DATE,
        BENEFIT_STATUS, SCHEDULED_PAYMENT, REASON_CODE
    )
    SELECT
        -- DETERM_ID (VARCHAR(10) 길이 준수)
        CONCAT('D', DATE_FORMAT(NOW(), '%y%m%d'), LPAD(ROW_NUMBER() OVER(ORDER BY U.USER_ID), 3, '0')) AS DETERM_ID,
        U.USER_ID,
        PC.CRITERIA_ID,
        NOW() AS DETERM_DATE,
        
        -- BENEFIT_STATUS 판정 로직
        CASE
            WHEN (F.TOTAL_INCOME <= PC.FINANCIAL_INCOME_LIMIT)
             AND (F.PROPERTY_TAX_BASE_SUM <= PC.PROPERTY_TAX_LIMIT)
             AND (F.HEALTH_INSURANCE_PREMIUM <= HIC.PREMIUM_UPPER_LIMIT)
            THEN 'Y' ELSE 'N'
        END AS BENEFIT_STATUS,

        -- SCHEDULED_PAYMENT 지급액 로직
        CASE
            WHEN (F.TOTAL_INCOME <= PC.FINANCIAL_INCOME_LIMIT)
             AND (F.PROPERTY_TAX_BASE_SUM <= PC.PROPERTY_TAX_LIMIT)
             AND (F.HEALTH_INSURANCE_PREMIUM <= HIC.PREMIUM_UPPER_LIMIT)
            THEN
                CASE H.QUALIFICATION_CODE
                    WHEN 'BASIC' THEN PC.BASIC_RECIPIENT_BASE
                    WHEN 'SUBBASIC' THEN PC.SUB_BASIC_BASE
                    WHEN 'GENERAL' THEN PC.GENERAL_CITIZEN_BASE
                    WHEN 'TOP10' THEN PC.TOP_10_BASE
                    ELSE PC.GENERAL_CITIZEN_BASE
                END
            ELSE 0
        END AS SCHEDULED_PAYMENT,

        -- REASON_CODE 탈락 사유 로직 (순위: 재산 > 건보료 > 소득)
        CASE
            WHEN F.PROPERTY_TAX_BASE_SUM > PC.PROPERTY_TAX_LIMIT THEN 'ASSET_EXCESS'
            WHEN F.HEALTH_INSURANCE_PREMIUM > HIC.PREMIUM_UPPER_LIMIT THEN 'HI_PREMIUM_EXCESS'
            WHEN F.TOTAL_INCOME > PC.FINANCIAL_INCOME_LIMIT THEN 'FINANCIAL_EXCESS'
            ELSE NULL
        END AS REASON_CODE

    FROM 
        USER U
    JOIN FINANCIAL_INFO F ON U.USER_ID = F.USER_ID
    JOIN HOUSEHOLD H ON U.HOUSEHOLD_ID = H.HOUSEHOLD_ID
    JOIN POLICY_CRITERIA PC ON PC.CRITERIA_ID = 'P2025-1' 
    JOIN HEALTH_INSURANCE_CRITERIA HIC ON 
        HIC.CRITERIA_ID = PC.CRITERIA_ID AND 
        TRIM(HIC.HOUSEHOLD_TYPE) = TRIM(H.INCOME_SOURCE_TYPE) AND 
        HIC.MEMBER_COUNT_TYPE = H.MEMBER_COUNT AND   
        TRIM(HIC.SUBSCRIBER_TYPE) = TRIM(F.SUBSCRIBER_TYPE)
    ORDER BY U.USER_ID;

END //

DELIMITER ;