-- ----------------------------------------------------------------
-- 0. 데이터베이스 생성 및 선택
-- ----------------------------------------------------------------
-- 이전 오류 방지 및 새로운 프로젝트 시작
CREATE DATABASE IF NOT EXISTS minsaeng DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE minsaeng;

-- ----------------------------------------------------------------
-- 1. 부모 테이블 생성 (참조되지 않거나 순환 참조를 피하기 위해 먼저 생성)
-- ----------------------------------------------------------------

-- 탈락 사유 정의 테이블 (REJECTION_REASON)
CREATE TABLE REJECTION_REASON (
    REASON_CODE VARCHAR(50) NOT NULL PRIMARY KEY,
    REASON_TYPE VARCHAR(50) NOT NULL,
    REASON_DESCRIPTION VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 정책 기준 정의 테이블 (POLICY_CRITERIA)
CREATE TABLE POLICY_CRITERIA (
    CRITERIA_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    POLICY_NAME VARCHAR(100) NOT NULL,
    PROPERTY_TAX_LIMIT BIGINT NOT NULL,
    FINANCIAL_INCOME_LIMIT BIGINT NOT NULL,
    BASIC_RECIPIENT_BASE BIGINT NOT NULL,
    SUB_BASIC_BASE BIGINT NOT NULL,
    GENERAL_CITIZEN_BASE BIGINT NOT NULL,
    TOP_10_BASE BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 가구 구성 정보 테이블 (HOUSEHOLD)
-- USER 테이블에 의해 참조되므로 먼저 생성됩니다. 순환 참조 FK는 나중에 추가됩니다.
CREATE TABLE HOUSEHOLD (
    HOUSEHOLD_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    HEAD_USER_ID VARCHAR(10) NOT NULL, -- FK는 3번 ALTER TABLE에서 추가
    MEMBER_COUNT INT NOT NULL,
    INCOME_SOURCE_TYPE VARCHAR(50) NOT NULL,
    QUALIFICATION_CODE VARCHAR(50) NOT NULL,
    SINGLE_PERSON_ADJ TINYINT(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 건강보험료 기준표 (HEALTH_INSURANCE_CRITERIA)
CREATE TABLE HEALTH_INSURANCE_CRITERIA (
    HI_CRIT_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    CRITERIA_ID VARCHAR(10) NOT NULL, 
    HOUSEHOLD_TYPE VARCHAR(50) NOT NULL,
    MEMBER_COUNT_TYPE VARCHAR(50) NOT NULL,
    SUBSCRIBER_TYPE VARCHAR(50) NOT NULL,
    PREMIUM_UPPER_LIMIT INT NOT NULL,
    
    FOREIGN KEY (CRITERIA_ID) REFERENCES POLICY_CRITERIA (CRITERIA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ----------------------------------------------------------------
-- 2. 자식 테이블 생성 (외래 키 설정)
-- ----------------------------------------------------------------

-- 사용자 기본 정보 테이블 (USER)
-- HOUSEHOLD 테이블을 참조합니다.
CREATE TABLE USER (
    USER_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    ADDRESS VARCHAR(100) DEFAULT NULL,
    HOUSEHOLD_ID VARCHAR(10) NOT NULL, 
    
    FOREIGN KEY (HOUSEHOLD_ID) REFERENCES HOUSEHOLD (HOUSEHOLD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 경제 정보 테이블 (FINANCIAL_INFO)
-- USER 테이블을 참조합니다.
CREATE TABLE FINANCIAL_INFO (
    INFO_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(10) NOT NULL, 
    SUBSCRIBER_TYPE VARCHAR(50) NOT NULL,
    TOTAL_INCOME BIGINT NOT NULL,
    FINANCIAL_INCOME_SUM BIGINT NOT NULL,
    PROPERTY_TAX_BASE_SUM BIGINT NOT NULL,
    HEALTH_INSURANCE_PREMIUM BIGINT NOT NULL,
    
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 판정 결과 테이블 (DETERMINATION)
-- USER, POLICY_CRITERIA, REJECTION_REASON 테이블을 참조합니다.
CREATE TABLE DETERMINATION (
    DETERM_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(10) NOT NULL,
    CRITERIA_ID VARCHAR(10) NOT NULL,
    DETERM_DATE DATETIME NOT NULL,
    BENEFIT_STATUS CHAR(1) NOT NULL,
    SCHEDULED_PAYMENT INT DEFAULT NULL,
    REASON_CODE VARCHAR(100) DEFAULT NULL, 
    
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
    FOREIGN KEY (CRITERIA_ID) REFERENCES POLICY_CRITERIA (CRITERIA_ID),
    FOREIGN KEY (REASON_CODE) REFERENCES REJECTION_REASON (REASON_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ----------------------------------------------------------------
-- 3. 순환 참조 해결 (ALTER TABLE)
-- ----------------------------------------------------------------

-- HOUSEHOLD 테이블에 HEAD_USER_ID FK 추가 (USER 테이블을 참조)
-- USER 테이블이 생성된 후에만 이 명령이 실행되어야 순환 참조 오류가 발생하지 않습니다.
ALTER TABLE HOUSEHOLD
ADD CONSTRAINT fk_head_user
FOREIGN KEY (HEAD_USER_ID) REFERENCES USER (USER_ID);